/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Database_H
#define Database_H

#include <thrift/TDispatchProcessor.h>
#include "idaas_types.h"

namespace idaas {

class DatabaseIf {
 public:
  virtual ~DatabaseIf() {}
  virtual void listEnums(std::vector<ida_enum> & _return) = 0;
  virtual void storeEnum(const ida_enum& _enum) = 0;
  virtual void deleteEnum(const int32_t id) = 0;
};

class DatabaseIfFactory {
 public:
  typedef DatabaseIf Handler;

  virtual ~DatabaseIfFactory() {}

  virtual DatabaseIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(DatabaseIf* /* handler */) = 0;
};

class DatabaseIfSingletonFactory : virtual public DatabaseIfFactory {
 public:
  DatabaseIfSingletonFactory(const boost::shared_ptr<DatabaseIf>& iface) : iface_(iface) {}
  virtual ~DatabaseIfSingletonFactory() {}

  virtual DatabaseIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(DatabaseIf* /* handler */) {}

 protected:
  boost::shared_ptr<DatabaseIf> iface_;
};

class DatabaseNull : virtual public DatabaseIf {
 public:
  virtual ~DatabaseNull() {}
  void listEnums(std::vector<ida_enum> & /* _return */) {
    return;
  }
  void storeEnum(const ida_enum& /* _enum */) {
    return;
  }
  void deleteEnum(const int32_t /* id */) {
    return;
  }
};


class Database_listEnums_args {
 public:

  Database_listEnums_args() {
  }

  virtual ~Database_listEnums_args() throw() {}


  bool operator == (const Database_listEnums_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Database_listEnums_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Database_listEnums_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Database_listEnums_pargs {
 public:


  virtual ~Database_listEnums_pargs() throw() {}


  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Database_listEnums_result__isset {
  _Database_listEnums_result__isset() : success(false) {}
  bool success;
} _Database_listEnums_result__isset;

class Database_listEnums_result {
 public:

  Database_listEnums_result() {
  }

  virtual ~Database_listEnums_result() throw() {}

  std::vector<ida_enum>  success;

  _Database_listEnums_result__isset __isset;

  void __set_success(const std::vector<ida_enum> & val) {
    success = val;
  }

  bool operator == (const Database_listEnums_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Database_listEnums_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Database_listEnums_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Database_listEnums_presult__isset {
  _Database_listEnums_presult__isset() : success(false) {}
  bool success;
} _Database_listEnums_presult__isset;

class Database_listEnums_presult {
 public:


  virtual ~Database_listEnums_presult() throw() {}

  std::vector<ida_enum> * success;

  _Database_listEnums_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Database_storeEnum_args__isset {
  _Database_storeEnum_args__isset() : _enum(false) {}
  bool _enum;
} _Database_storeEnum_args__isset;

class Database_storeEnum_args {
 public:

  Database_storeEnum_args() {
  }

  virtual ~Database_storeEnum_args() throw() {}

  ida_enum _enum;

  _Database_storeEnum_args__isset __isset;

  void __set__enum(const ida_enum& val) {
    _enum = val;
  }

  bool operator == (const Database_storeEnum_args & rhs) const
  {
    if (!(_enum == rhs._enum))
      return false;
    return true;
  }
  bool operator != (const Database_storeEnum_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Database_storeEnum_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Database_storeEnum_pargs {
 public:


  virtual ~Database_storeEnum_pargs() throw() {}

  const ida_enum* _enum;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Database_storeEnum_result {
 public:

  Database_storeEnum_result() {
  }

  virtual ~Database_storeEnum_result() throw() {}


  bool operator == (const Database_storeEnum_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Database_storeEnum_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Database_storeEnum_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Database_storeEnum_presult {
 public:


  virtual ~Database_storeEnum_presult() throw() {}


  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Database_deleteEnum_args__isset {
  _Database_deleteEnum_args__isset() : id(false) {}
  bool id;
} _Database_deleteEnum_args__isset;

class Database_deleteEnum_args {
 public:

  Database_deleteEnum_args() : id(0) {
  }

  virtual ~Database_deleteEnum_args() throw() {}

  int32_t id;

  _Database_deleteEnum_args__isset __isset;

  void __set_id(const int32_t val) {
    id = val;
  }

  bool operator == (const Database_deleteEnum_args & rhs) const
  {
    if (!(id == rhs.id))
      return false;
    return true;
  }
  bool operator != (const Database_deleteEnum_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Database_deleteEnum_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Database_deleteEnum_pargs {
 public:


  virtual ~Database_deleteEnum_pargs() throw() {}

  const int32_t* id;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Database_deleteEnum_result {
 public:

  Database_deleteEnum_result() {
  }

  virtual ~Database_deleteEnum_result() throw() {}


  bool operator == (const Database_deleteEnum_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Database_deleteEnum_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Database_deleteEnum_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Database_deleteEnum_presult {
 public:


  virtual ~Database_deleteEnum_presult() throw() {}


  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class DatabaseClient : virtual public DatabaseIf {
 public:
  DatabaseClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  DatabaseClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void listEnums(std::vector<ida_enum> & _return);
  void send_listEnums();
  void recv_listEnums(std::vector<ida_enum> & _return);
  void storeEnum(const ida_enum& _enum);
  void send_storeEnum(const ida_enum& _enum);
  void recv_storeEnum();
  void deleteEnum(const int32_t id);
  void send_deleteEnum(const int32_t id);
  void recv_deleteEnum();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class DatabaseProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<DatabaseIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (DatabaseProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_listEnums(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_storeEnum(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_deleteEnum(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  DatabaseProcessor(boost::shared_ptr<DatabaseIf> iface) :
    iface_(iface) {
    processMap_["listEnums"] = &DatabaseProcessor::process_listEnums;
    processMap_["storeEnum"] = &DatabaseProcessor::process_storeEnum;
    processMap_["deleteEnum"] = &DatabaseProcessor::process_deleteEnum;
  }

  virtual ~DatabaseProcessor() {}
};

class DatabaseProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  DatabaseProcessorFactory(const ::boost::shared_ptr< DatabaseIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< DatabaseIfFactory > handlerFactory_;
};

class DatabaseMultiface : virtual public DatabaseIf {
 public:
  DatabaseMultiface(std::vector<boost::shared_ptr<DatabaseIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~DatabaseMultiface() {}
 protected:
  std::vector<boost::shared_ptr<DatabaseIf> > ifaces_;
  DatabaseMultiface() {}
  void add(boost::shared_ptr<DatabaseIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void listEnums(std::vector<ida_enum> & _return) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->listEnums(_return);
    }
    ifaces_[i]->listEnums(_return);
    return;
  }

  void storeEnum(const ida_enum& _enum) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->storeEnum(_enum);
    }
    ifaces_[i]->storeEnum(_enum);
  }

  void deleteEnum(const int32_t id) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->deleteEnum(id);
    }
    ifaces_[i]->deleteEnum(id);
  }

};

} // namespace

#endif
