/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Database_H
#define Database_H

#include <thrift/TDispatchProcessor.h>
#include "idaas_types.h"

namespace idaas {

class DatabaseIf {
 public:
  virtual ~DatabaseIf() {}
  virtual void listEnums(std::vector<ida_enum> & _return) = 0;
  virtual bool storeEnum(const ida_enum& _enum) = 0;
  virtual bool storeEnums(const std::vector<ida_enum> & enums) = 0;
  virtual void deleteEnum(const std::string& name) = 0;
  virtual void listStructures(std::vector<IdaStruct> & _return) = 0;
  virtual bool storeStructure(const IdaStruct& _struct) = 0;
  virtual bool storeStructures(const std::vector<IdaStruct> & structs) = 0;
  virtual void deleteStruct(const std::string& name) = 0;
  virtual void listStrings(std::vector<ida_string> & _return) = 0;
  virtual void xrefsTo(std::vector<IdaRef> & _return, const int32_t address, const IdaRefType::type refType) = 0;
  virtual void xrefsFrom(std::vector<IdaRef> & _return, const int32_t address, const IdaRefType::type refType) = 0;
  virtual void fetchInstruction(IdaInstruction& _return, const int32_t address) = 0;
  virtual void listFunctions(std::vector<IdaFunction> & _return) = 0;
  virtual void getFunctionFrame(IdaFunctionFrame& _return, const int32_t address) = 0;
  virtual void parseTypeDeclaration(IdaTypeInfo& _return, const std::string& typeDeclaration) = 0;
  virtual void formatTypeInfo(std::string& _return, const IdaTypeInfo& typeInfo) = 0;
  virtual void waitBackgroundTasks() = 0;
};

class DatabaseIfFactory {
 public:
  typedef DatabaseIf Handler;

  virtual ~DatabaseIfFactory() {}

  virtual DatabaseIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(DatabaseIf* /* handler */) = 0;
};

class DatabaseIfSingletonFactory : virtual public DatabaseIfFactory {
 public:
  DatabaseIfSingletonFactory(const boost::shared_ptr<DatabaseIf>& iface) : iface_(iface) {}
  virtual ~DatabaseIfSingletonFactory() {}

  virtual DatabaseIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(DatabaseIf* /* handler */) {}

 protected:
  boost::shared_ptr<DatabaseIf> iface_;
};

class DatabaseNull : virtual public DatabaseIf {
 public:
  virtual ~DatabaseNull() {}
  void listEnums(std::vector<ida_enum> & /* _return */) {
    return;
  }
  bool storeEnum(const ida_enum& /* _enum */) {
    bool _return = false;
    return _return;
  }
  bool storeEnums(const std::vector<ida_enum> & /* enums */) {
    bool _return = false;
    return _return;
  }
  void deleteEnum(const std::string& /* name */) {
    return;
  }
  void listStructures(std::vector<IdaStruct> & /* _return */) {
    return;
  }
  bool storeStructure(const IdaStruct& /* _struct */) {
    bool _return = false;
    return _return;
  }
  bool storeStructures(const std::vector<IdaStruct> & /* structs */) {
    bool _return = false;
    return _return;
  }
  void deleteStruct(const std::string& /* name */) {
    return;
  }
  void listStrings(std::vector<ida_string> & /* _return */) {
    return;
  }
  void xrefsTo(std::vector<IdaRef> & /* _return */, const int32_t /* address */, const IdaRefType::type /* refType */) {
    return;
  }
  void xrefsFrom(std::vector<IdaRef> & /* _return */, const int32_t /* address */, const IdaRefType::type /* refType */) {
    return;
  }
  void fetchInstruction(IdaInstruction& /* _return */, const int32_t /* address */) {
    return;
  }
  void listFunctions(std::vector<IdaFunction> & /* _return */) {
    return;
  }
  void getFunctionFrame(IdaFunctionFrame& /* _return */, const int32_t /* address */) {
    return;
  }
  void parseTypeDeclaration(IdaTypeInfo& /* _return */, const std::string& /* typeDeclaration */) {
    return;
  }
  void formatTypeInfo(std::string& /* _return */, const IdaTypeInfo& /* typeInfo */) {
    return;
  }
  void waitBackgroundTasks() {
    return;
  }
};


class Database_listEnums_args {
 public:

  Database_listEnums_args() {
  }

  virtual ~Database_listEnums_args() throw() {}


  bool operator == (const Database_listEnums_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Database_listEnums_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Database_listEnums_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Database_listEnums_pargs {
 public:


  virtual ~Database_listEnums_pargs() throw() {}


  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Database_listEnums_result__isset {
  _Database_listEnums_result__isset() : success(false) {}
  bool success;
} _Database_listEnums_result__isset;

class Database_listEnums_result {
 public:

  Database_listEnums_result() {
  }

  virtual ~Database_listEnums_result() throw() {}

  std::vector<ida_enum>  success;

  _Database_listEnums_result__isset __isset;

  void __set_success(const std::vector<ida_enum> & val) {
    success = val;
  }

  bool operator == (const Database_listEnums_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Database_listEnums_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Database_listEnums_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Database_listEnums_presult__isset {
  _Database_listEnums_presult__isset() : success(false) {}
  bool success;
} _Database_listEnums_presult__isset;

class Database_listEnums_presult {
 public:


  virtual ~Database_listEnums_presult() throw() {}

  std::vector<ida_enum> * success;

  _Database_listEnums_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Database_storeEnum_args__isset {
  _Database_storeEnum_args__isset() : _enum(false) {}
  bool _enum;
} _Database_storeEnum_args__isset;

class Database_storeEnum_args {
 public:

  Database_storeEnum_args() {
  }

  virtual ~Database_storeEnum_args() throw() {}

  ida_enum _enum;

  _Database_storeEnum_args__isset __isset;

  void __set__enum(const ida_enum& val) {
    _enum = val;
  }

  bool operator == (const Database_storeEnum_args & rhs) const
  {
    if (!(_enum == rhs._enum))
      return false;
    return true;
  }
  bool operator != (const Database_storeEnum_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Database_storeEnum_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Database_storeEnum_pargs {
 public:


  virtual ~Database_storeEnum_pargs() throw() {}

  const ida_enum* _enum;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Database_storeEnum_result__isset {
  _Database_storeEnum_result__isset() : success(false) {}
  bool success;
} _Database_storeEnum_result__isset;

class Database_storeEnum_result {
 public:

  Database_storeEnum_result() : success(0) {
  }

  virtual ~Database_storeEnum_result() throw() {}

  bool success;

  _Database_storeEnum_result__isset __isset;

  void __set_success(const bool val) {
    success = val;
  }

  bool operator == (const Database_storeEnum_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Database_storeEnum_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Database_storeEnum_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Database_storeEnum_presult__isset {
  _Database_storeEnum_presult__isset() : success(false) {}
  bool success;
} _Database_storeEnum_presult__isset;

class Database_storeEnum_presult {
 public:


  virtual ~Database_storeEnum_presult() throw() {}

  bool* success;

  _Database_storeEnum_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Database_storeEnums_args__isset {
  _Database_storeEnums_args__isset() : enums(false) {}
  bool enums;
} _Database_storeEnums_args__isset;

class Database_storeEnums_args {
 public:

  Database_storeEnums_args() {
  }

  virtual ~Database_storeEnums_args() throw() {}

  std::vector<ida_enum>  enums;

  _Database_storeEnums_args__isset __isset;

  void __set_enums(const std::vector<ida_enum> & val) {
    enums = val;
  }

  bool operator == (const Database_storeEnums_args & rhs) const
  {
    if (!(enums == rhs.enums))
      return false;
    return true;
  }
  bool operator != (const Database_storeEnums_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Database_storeEnums_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Database_storeEnums_pargs {
 public:


  virtual ~Database_storeEnums_pargs() throw() {}

  const std::vector<ida_enum> * enums;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Database_storeEnums_result__isset {
  _Database_storeEnums_result__isset() : success(false) {}
  bool success;
} _Database_storeEnums_result__isset;

class Database_storeEnums_result {
 public:

  Database_storeEnums_result() : success(0) {
  }

  virtual ~Database_storeEnums_result() throw() {}

  bool success;

  _Database_storeEnums_result__isset __isset;

  void __set_success(const bool val) {
    success = val;
  }

  bool operator == (const Database_storeEnums_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Database_storeEnums_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Database_storeEnums_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Database_storeEnums_presult__isset {
  _Database_storeEnums_presult__isset() : success(false) {}
  bool success;
} _Database_storeEnums_presult__isset;

class Database_storeEnums_presult {
 public:


  virtual ~Database_storeEnums_presult() throw() {}

  bool* success;

  _Database_storeEnums_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Database_deleteEnum_args__isset {
  _Database_deleteEnum_args__isset() : name(false) {}
  bool name;
} _Database_deleteEnum_args__isset;

class Database_deleteEnum_args {
 public:

  Database_deleteEnum_args() : name() {
  }

  virtual ~Database_deleteEnum_args() throw() {}

  std::string name;

  _Database_deleteEnum_args__isset __isset;

  void __set_name(const std::string& val) {
    name = val;
  }

  bool operator == (const Database_deleteEnum_args & rhs) const
  {
    if (!(name == rhs.name))
      return false;
    return true;
  }
  bool operator != (const Database_deleteEnum_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Database_deleteEnum_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Database_deleteEnum_pargs {
 public:


  virtual ~Database_deleteEnum_pargs() throw() {}

  const std::string* name;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Database_deleteEnum_result {
 public:

  Database_deleteEnum_result() {
  }

  virtual ~Database_deleteEnum_result() throw() {}


  bool operator == (const Database_deleteEnum_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Database_deleteEnum_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Database_deleteEnum_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Database_deleteEnum_presult {
 public:


  virtual ~Database_deleteEnum_presult() throw() {}


  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class Database_listStructures_args {
 public:

  Database_listStructures_args() {
  }

  virtual ~Database_listStructures_args() throw() {}


  bool operator == (const Database_listStructures_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Database_listStructures_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Database_listStructures_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Database_listStructures_pargs {
 public:


  virtual ~Database_listStructures_pargs() throw() {}


  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Database_listStructures_result__isset {
  _Database_listStructures_result__isset() : success(false) {}
  bool success;
} _Database_listStructures_result__isset;

class Database_listStructures_result {
 public:

  Database_listStructures_result() {
  }

  virtual ~Database_listStructures_result() throw() {}

  std::vector<IdaStruct>  success;

  _Database_listStructures_result__isset __isset;

  void __set_success(const std::vector<IdaStruct> & val) {
    success = val;
  }

  bool operator == (const Database_listStructures_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Database_listStructures_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Database_listStructures_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Database_listStructures_presult__isset {
  _Database_listStructures_presult__isset() : success(false) {}
  bool success;
} _Database_listStructures_presult__isset;

class Database_listStructures_presult {
 public:


  virtual ~Database_listStructures_presult() throw() {}

  std::vector<IdaStruct> * success;

  _Database_listStructures_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Database_storeStructure_args__isset {
  _Database_storeStructure_args__isset() : _struct(false) {}
  bool _struct;
} _Database_storeStructure_args__isset;

class Database_storeStructure_args {
 public:

  Database_storeStructure_args() {
  }

  virtual ~Database_storeStructure_args() throw() {}

  IdaStruct _struct;

  _Database_storeStructure_args__isset __isset;

  void __set__struct(const IdaStruct& val) {
    _struct = val;
  }

  bool operator == (const Database_storeStructure_args & rhs) const
  {
    if (!(_struct == rhs._struct))
      return false;
    return true;
  }
  bool operator != (const Database_storeStructure_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Database_storeStructure_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Database_storeStructure_pargs {
 public:


  virtual ~Database_storeStructure_pargs() throw() {}

  const IdaStruct* _struct;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Database_storeStructure_result__isset {
  _Database_storeStructure_result__isset() : success(false) {}
  bool success;
} _Database_storeStructure_result__isset;

class Database_storeStructure_result {
 public:

  Database_storeStructure_result() : success(0) {
  }

  virtual ~Database_storeStructure_result() throw() {}

  bool success;

  _Database_storeStructure_result__isset __isset;

  void __set_success(const bool val) {
    success = val;
  }

  bool operator == (const Database_storeStructure_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Database_storeStructure_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Database_storeStructure_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Database_storeStructure_presult__isset {
  _Database_storeStructure_presult__isset() : success(false) {}
  bool success;
} _Database_storeStructure_presult__isset;

class Database_storeStructure_presult {
 public:


  virtual ~Database_storeStructure_presult() throw() {}

  bool* success;

  _Database_storeStructure_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Database_storeStructures_args__isset {
  _Database_storeStructures_args__isset() : structs(false) {}
  bool structs;
} _Database_storeStructures_args__isset;

class Database_storeStructures_args {
 public:

  Database_storeStructures_args() {
  }

  virtual ~Database_storeStructures_args() throw() {}

  std::vector<IdaStruct>  structs;

  _Database_storeStructures_args__isset __isset;

  void __set_structs(const std::vector<IdaStruct> & val) {
    structs = val;
  }

  bool operator == (const Database_storeStructures_args & rhs) const
  {
    if (!(structs == rhs.structs))
      return false;
    return true;
  }
  bool operator != (const Database_storeStructures_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Database_storeStructures_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Database_storeStructures_pargs {
 public:


  virtual ~Database_storeStructures_pargs() throw() {}

  const std::vector<IdaStruct> * structs;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Database_storeStructures_result__isset {
  _Database_storeStructures_result__isset() : success(false) {}
  bool success;
} _Database_storeStructures_result__isset;

class Database_storeStructures_result {
 public:

  Database_storeStructures_result() : success(0) {
  }

  virtual ~Database_storeStructures_result() throw() {}

  bool success;

  _Database_storeStructures_result__isset __isset;

  void __set_success(const bool val) {
    success = val;
  }

  bool operator == (const Database_storeStructures_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Database_storeStructures_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Database_storeStructures_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Database_storeStructures_presult__isset {
  _Database_storeStructures_presult__isset() : success(false) {}
  bool success;
} _Database_storeStructures_presult__isset;

class Database_storeStructures_presult {
 public:


  virtual ~Database_storeStructures_presult() throw() {}

  bool* success;

  _Database_storeStructures_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Database_deleteStruct_args__isset {
  _Database_deleteStruct_args__isset() : name(false) {}
  bool name;
} _Database_deleteStruct_args__isset;

class Database_deleteStruct_args {
 public:

  Database_deleteStruct_args() : name() {
  }

  virtual ~Database_deleteStruct_args() throw() {}

  std::string name;

  _Database_deleteStruct_args__isset __isset;

  void __set_name(const std::string& val) {
    name = val;
  }

  bool operator == (const Database_deleteStruct_args & rhs) const
  {
    if (!(name == rhs.name))
      return false;
    return true;
  }
  bool operator != (const Database_deleteStruct_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Database_deleteStruct_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Database_deleteStruct_pargs {
 public:


  virtual ~Database_deleteStruct_pargs() throw() {}

  const std::string* name;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Database_deleteStruct_result {
 public:

  Database_deleteStruct_result() {
  }

  virtual ~Database_deleteStruct_result() throw() {}


  bool operator == (const Database_deleteStruct_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Database_deleteStruct_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Database_deleteStruct_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Database_deleteStruct_presult {
 public:


  virtual ~Database_deleteStruct_presult() throw() {}


  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class Database_listStrings_args {
 public:

  Database_listStrings_args() {
  }

  virtual ~Database_listStrings_args() throw() {}


  bool operator == (const Database_listStrings_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Database_listStrings_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Database_listStrings_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Database_listStrings_pargs {
 public:


  virtual ~Database_listStrings_pargs() throw() {}


  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Database_listStrings_result__isset {
  _Database_listStrings_result__isset() : success(false) {}
  bool success;
} _Database_listStrings_result__isset;

class Database_listStrings_result {
 public:

  Database_listStrings_result() {
  }

  virtual ~Database_listStrings_result() throw() {}

  std::vector<ida_string>  success;

  _Database_listStrings_result__isset __isset;

  void __set_success(const std::vector<ida_string> & val) {
    success = val;
  }

  bool operator == (const Database_listStrings_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Database_listStrings_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Database_listStrings_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Database_listStrings_presult__isset {
  _Database_listStrings_presult__isset() : success(false) {}
  bool success;
} _Database_listStrings_presult__isset;

class Database_listStrings_presult {
 public:


  virtual ~Database_listStrings_presult() throw() {}

  std::vector<ida_string> * success;

  _Database_listStrings_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Database_xrefsTo_args__isset {
  _Database_xrefsTo_args__isset() : address(false), refType(false) {}
  bool address;
  bool refType;
} _Database_xrefsTo_args__isset;

class Database_xrefsTo_args {
 public:

  Database_xrefsTo_args() : address(0), refType((IdaRefType::type)0) {
  }

  virtual ~Database_xrefsTo_args() throw() {}

  int32_t address;
  IdaRefType::type refType;

  _Database_xrefsTo_args__isset __isset;

  void __set_address(const int32_t val) {
    address = val;
  }

  void __set_refType(const IdaRefType::type val) {
    refType = val;
  }

  bool operator == (const Database_xrefsTo_args & rhs) const
  {
    if (!(address == rhs.address))
      return false;
    if (!(refType == rhs.refType))
      return false;
    return true;
  }
  bool operator != (const Database_xrefsTo_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Database_xrefsTo_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Database_xrefsTo_pargs {
 public:


  virtual ~Database_xrefsTo_pargs() throw() {}

  const int32_t* address;
  const IdaRefType::type* refType;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Database_xrefsTo_result__isset {
  _Database_xrefsTo_result__isset() : success(false) {}
  bool success;
} _Database_xrefsTo_result__isset;

class Database_xrefsTo_result {
 public:

  Database_xrefsTo_result() {
  }

  virtual ~Database_xrefsTo_result() throw() {}

  std::vector<IdaRef>  success;

  _Database_xrefsTo_result__isset __isset;

  void __set_success(const std::vector<IdaRef> & val) {
    success = val;
  }

  bool operator == (const Database_xrefsTo_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Database_xrefsTo_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Database_xrefsTo_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Database_xrefsTo_presult__isset {
  _Database_xrefsTo_presult__isset() : success(false) {}
  bool success;
} _Database_xrefsTo_presult__isset;

class Database_xrefsTo_presult {
 public:


  virtual ~Database_xrefsTo_presult() throw() {}

  std::vector<IdaRef> * success;

  _Database_xrefsTo_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Database_xrefsFrom_args__isset {
  _Database_xrefsFrom_args__isset() : address(false), refType(false) {}
  bool address;
  bool refType;
} _Database_xrefsFrom_args__isset;

class Database_xrefsFrom_args {
 public:

  Database_xrefsFrom_args() : address(0), refType((IdaRefType::type)0) {
  }

  virtual ~Database_xrefsFrom_args() throw() {}

  int32_t address;
  IdaRefType::type refType;

  _Database_xrefsFrom_args__isset __isset;

  void __set_address(const int32_t val) {
    address = val;
  }

  void __set_refType(const IdaRefType::type val) {
    refType = val;
  }

  bool operator == (const Database_xrefsFrom_args & rhs) const
  {
    if (!(address == rhs.address))
      return false;
    if (!(refType == rhs.refType))
      return false;
    return true;
  }
  bool operator != (const Database_xrefsFrom_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Database_xrefsFrom_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Database_xrefsFrom_pargs {
 public:


  virtual ~Database_xrefsFrom_pargs() throw() {}

  const int32_t* address;
  const IdaRefType::type* refType;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Database_xrefsFrom_result__isset {
  _Database_xrefsFrom_result__isset() : success(false) {}
  bool success;
} _Database_xrefsFrom_result__isset;

class Database_xrefsFrom_result {
 public:

  Database_xrefsFrom_result() {
  }

  virtual ~Database_xrefsFrom_result() throw() {}

  std::vector<IdaRef>  success;

  _Database_xrefsFrom_result__isset __isset;

  void __set_success(const std::vector<IdaRef> & val) {
    success = val;
  }

  bool operator == (const Database_xrefsFrom_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Database_xrefsFrom_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Database_xrefsFrom_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Database_xrefsFrom_presult__isset {
  _Database_xrefsFrom_presult__isset() : success(false) {}
  bool success;
} _Database_xrefsFrom_presult__isset;

class Database_xrefsFrom_presult {
 public:


  virtual ~Database_xrefsFrom_presult() throw() {}

  std::vector<IdaRef> * success;

  _Database_xrefsFrom_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Database_fetchInstruction_args__isset {
  _Database_fetchInstruction_args__isset() : address(false) {}
  bool address;
} _Database_fetchInstruction_args__isset;

class Database_fetchInstruction_args {
 public:

  Database_fetchInstruction_args() : address(0) {
  }

  virtual ~Database_fetchInstruction_args() throw() {}

  int32_t address;

  _Database_fetchInstruction_args__isset __isset;

  void __set_address(const int32_t val) {
    address = val;
  }

  bool operator == (const Database_fetchInstruction_args & rhs) const
  {
    if (!(address == rhs.address))
      return false;
    return true;
  }
  bool operator != (const Database_fetchInstruction_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Database_fetchInstruction_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Database_fetchInstruction_pargs {
 public:


  virtual ~Database_fetchInstruction_pargs() throw() {}

  const int32_t* address;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Database_fetchInstruction_result__isset {
  _Database_fetchInstruction_result__isset() : success(false) {}
  bool success;
} _Database_fetchInstruction_result__isset;

class Database_fetchInstruction_result {
 public:

  Database_fetchInstruction_result() {
  }

  virtual ~Database_fetchInstruction_result() throw() {}

  IdaInstruction success;

  _Database_fetchInstruction_result__isset __isset;

  void __set_success(const IdaInstruction& val) {
    success = val;
  }

  bool operator == (const Database_fetchInstruction_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Database_fetchInstruction_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Database_fetchInstruction_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Database_fetchInstruction_presult__isset {
  _Database_fetchInstruction_presult__isset() : success(false) {}
  bool success;
} _Database_fetchInstruction_presult__isset;

class Database_fetchInstruction_presult {
 public:


  virtual ~Database_fetchInstruction_presult() throw() {}

  IdaInstruction* success;

  _Database_fetchInstruction_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class Database_listFunctions_args {
 public:

  Database_listFunctions_args() {
  }

  virtual ~Database_listFunctions_args() throw() {}


  bool operator == (const Database_listFunctions_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Database_listFunctions_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Database_listFunctions_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Database_listFunctions_pargs {
 public:


  virtual ~Database_listFunctions_pargs() throw() {}


  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Database_listFunctions_result__isset {
  _Database_listFunctions_result__isset() : success(false) {}
  bool success;
} _Database_listFunctions_result__isset;

class Database_listFunctions_result {
 public:

  Database_listFunctions_result() {
  }

  virtual ~Database_listFunctions_result() throw() {}

  std::vector<IdaFunction>  success;

  _Database_listFunctions_result__isset __isset;

  void __set_success(const std::vector<IdaFunction> & val) {
    success = val;
  }

  bool operator == (const Database_listFunctions_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Database_listFunctions_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Database_listFunctions_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Database_listFunctions_presult__isset {
  _Database_listFunctions_presult__isset() : success(false) {}
  bool success;
} _Database_listFunctions_presult__isset;

class Database_listFunctions_presult {
 public:


  virtual ~Database_listFunctions_presult() throw() {}

  std::vector<IdaFunction> * success;

  _Database_listFunctions_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Database_getFunctionFrame_args__isset {
  _Database_getFunctionFrame_args__isset() : address(false) {}
  bool address;
} _Database_getFunctionFrame_args__isset;

class Database_getFunctionFrame_args {
 public:

  Database_getFunctionFrame_args() : address(0) {
  }

  virtual ~Database_getFunctionFrame_args() throw() {}

  int32_t address;

  _Database_getFunctionFrame_args__isset __isset;

  void __set_address(const int32_t val) {
    address = val;
  }

  bool operator == (const Database_getFunctionFrame_args & rhs) const
  {
    if (!(address == rhs.address))
      return false;
    return true;
  }
  bool operator != (const Database_getFunctionFrame_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Database_getFunctionFrame_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Database_getFunctionFrame_pargs {
 public:


  virtual ~Database_getFunctionFrame_pargs() throw() {}

  const int32_t* address;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Database_getFunctionFrame_result__isset {
  _Database_getFunctionFrame_result__isset() : success(false) {}
  bool success;
} _Database_getFunctionFrame_result__isset;

class Database_getFunctionFrame_result {
 public:

  Database_getFunctionFrame_result() {
  }

  virtual ~Database_getFunctionFrame_result() throw() {}

  IdaFunctionFrame success;

  _Database_getFunctionFrame_result__isset __isset;

  void __set_success(const IdaFunctionFrame& val) {
    success = val;
  }

  bool operator == (const Database_getFunctionFrame_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Database_getFunctionFrame_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Database_getFunctionFrame_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Database_getFunctionFrame_presult__isset {
  _Database_getFunctionFrame_presult__isset() : success(false) {}
  bool success;
} _Database_getFunctionFrame_presult__isset;

class Database_getFunctionFrame_presult {
 public:


  virtual ~Database_getFunctionFrame_presult() throw() {}

  IdaFunctionFrame* success;

  _Database_getFunctionFrame_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Database_parseTypeDeclaration_args__isset {
  _Database_parseTypeDeclaration_args__isset() : typeDeclaration(false) {}
  bool typeDeclaration;
} _Database_parseTypeDeclaration_args__isset;

class Database_parseTypeDeclaration_args {
 public:

  Database_parseTypeDeclaration_args() : typeDeclaration() {
  }

  virtual ~Database_parseTypeDeclaration_args() throw() {}

  std::string typeDeclaration;

  _Database_parseTypeDeclaration_args__isset __isset;

  void __set_typeDeclaration(const std::string& val) {
    typeDeclaration = val;
  }

  bool operator == (const Database_parseTypeDeclaration_args & rhs) const
  {
    if (!(typeDeclaration == rhs.typeDeclaration))
      return false;
    return true;
  }
  bool operator != (const Database_parseTypeDeclaration_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Database_parseTypeDeclaration_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Database_parseTypeDeclaration_pargs {
 public:


  virtual ~Database_parseTypeDeclaration_pargs() throw() {}

  const std::string* typeDeclaration;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Database_parseTypeDeclaration_result__isset {
  _Database_parseTypeDeclaration_result__isset() : success(false) {}
  bool success;
} _Database_parseTypeDeclaration_result__isset;

class Database_parseTypeDeclaration_result {
 public:

  Database_parseTypeDeclaration_result() {
  }

  virtual ~Database_parseTypeDeclaration_result() throw() {}

  IdaTypeInfo success;

  _Database_parseTypeDeclaration_result__isset __isset;

  void __set_success(const IdaTypeInfo& val) {
    success = val;
  }

  bool operator == (const Database_parseTypeDeclaration_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Database_parseTypeDeclaration_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Database_parseTypeDeclaration_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Database_parseTypeDeclaration_presult__isset {
  _Database_parseTypeDeclaration_presult__isset() : success(false) {}
  bool success;
} _Database_parseTypeDeclaration_presult__isset;

class Database_parseTypeDeclaration_presult {
 public:


  virtual ~Database_parseTypeDeclaration_presult() throw() {}

  IdaTypeInfo* success;

  _Database_parseTypeDeclaration_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Database_formatTypeInfo_args__isset {
  _Database_formatTypeInfo_args__isset() : typeInfo(false) {}
  bool typeInfo;
} _Database_formatTypeInfo_args__isset;

class Database_formatTypeInfo_args {
 public:

  Database_formatTypeInfo_args() {
  }

  virtual ~Database_formatTypeInfo_args() throw() {}

  IdaTypeInfo typeInfo;

  _Database_formatTypeInfo_args__isset __isset;

  void __set_typeInfo(const IdaTypeInfo& val) {
    typeInfo = val;
  }

  bool operator == (const Database_formatTypeInfo_args & rhs) const
  {
    if (!(typeInfo == rhs.typeInfo))
      return false;
    return true;
  }
  bool operator != (const Database_formatTypeInfo_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Database_formatTypeInfo_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Database_formatTypeInfo_pargs {
 public:


  virtual ~Database_formatTypeInfo_pargs() throw() {}

  const IdaTypeInfo* typeInfo;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Database_formatTypeInfo_result__isset {
  _Database_formatTypeInfo_result__isset() : success(false) {}
  bool success;
} _Database_formatTypeInfo_result__isset;

class Database_formatTypeInfo_result {
 public:

  Database_formatTypeInfo_result() : success() {
  }

  virtual ~Database_formatTypeInfo_result() throw() {}

  std::string success;

  _Database_formatTypeInfo_result__isset __isset;

  void __set_success(const std::string& val) {
    success = val;
  }

  bool operator == (const Database_formatTypeInfo_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Database_formatTypeInfo_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Database_formatTypeInfo_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Database_formatTypeInfo_presult__isset {
  _Database_formatTypeInfo_presult__isset() : success(false) {}
  bool success;
} _Database_formatTypeInfo_presult__isset;

class Database_formatTypeInfo_presult {
 public:


  virtual ~Database_formatTypeInfo_presult() throw() {}

  std::string* success;

  _Database_formatTypeInfo_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class Database_waitBackgroundTasks_args {
 public:

  Database_waitBackgroundTasks_args() {
  }

  virtual ~Database_waitBackgroundTasks_args() throw() {}


  bool operator == (const Database_waitBackgroundTasks_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Database_waitBackgroundTasks_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Database_waitBackgroundTasks_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Database_waitBackgroundTasks_pargs {
 public:


  virtual ~Database_waitBackgroundTasks_pargs() throw() {}


  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Database_waitBackgroundTasks_result {
 public:

  Database_waitBackgroundTasks_result() {
  }

  virtual ~Database_waitBackgroundTasks_result() throw() {}


  bool operator == (const Database_waitBackgroundTasks_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Database_waitBackgroundTasks_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Database_waitBackgroundTasks_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Database_waitBackgroundTasks_presult {
 public:


  virtual ~Database_waitBackgroundTasks_presult() throw() {}


  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class DatabaseClient : virtual public DatabaseIf {
 public:
  DatabaseClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  DatabaseClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void listEnums(std::vector<ida_enum> & _return);
  void send_listEnums();
  void recv_listEnums(std::vector<ida_enum> & _return);
  bool storeEnum(const ida_enum& _enum);
  void send_storeEnum(const ida_enum& _enum);
  bool recv_storeEnum();
  bool storeEnums(const std::vector<ida_enum> & enums);
  void send_storeEnums(const std::vector<ida_enum> & enums);
  bool recv_storeEnums();
  void deleteEnum(const std::string& name);
  void send_deleteEnum(const std::string& name);
  void recv_deleteEnum();
  void listStructures(std::vector<IdaStruct> & _return);
  void send_listStructures();
  void recv_listStructures(std::vector<IdaStruct> & _return);
  bool storeStructure(const IdaStruct& _struct);
  void send_storeStructure(const IdaStruct& _struct);
  bool recv_storeStructure();
  bool storeStructures(const std::vector<IdaStruct> & structs);
  void send_storeStructures(const std::vector<IdaStruct> & structs);
  bool recv_storeStructures();
  void deleteStruct(const std::string& name);
  void send_deleteStruct(const std::string& name);
  void recv_deleteStruct();
  void listStrings(std::vector<ida_string> & _return);
  void send_listStrings();
  void recv_listStrings(std::vector<ida_string> & _return);
  void xrefsTo(std::vector<IdaRef> & _return, const int32_t address, const IdaRefType::type refType);
  void send_xrefsTo(const int32_t address, const IdaRefType::type refType);
  void recv_xrefsTo(std::vector<IdaRef> & _return);
  void xrefsFrom(std::vector<IdaRef> & _return, const int32_t address, const IdaRefType::type refType);
  void send_xrefsFrom(const int32_t address, const IdaRefType::type refType);
  void recv_xrefsFrom(std::vector<IdaRef> & _return);
  void fetchInstruction(IdaInstruction& _return, const int32_t address);
  void send_fetchInstruction(const int32_t address);
  void recv_fetchInstruction(IdaInstruction& _return);
  void listFunctions(std::vector<IdaFunction> & _return);
  void send_listFunctions();
  void recv_listFunctions(std::vector<IdaFunction> & _return);
  void getFunctionFrame(IdaFunctionFrame& _return, const int32_t address);
  void send_getFunctionFrame(const int32_t address);
  void recv_getFunctionFrame(IdaFunctionFrame& _return);
  void parseTypeDeclaration(IdaTypeInfo& _return, const std::string& typeDeclaration);
  void send_parseTypeDeclaration(const std::string& typeDeclaration);
  void recv_parseTypeDeclaration(IdaTypeInfo& _return);
  void formatTypeInfo(std::string& _return, const IdaTypeInfo& typeInfo);
  void send_formatTypeInfo(const IdaTypeInfo& typeInfo);
  void recv_formatTypeInfo(std::string& _return);
  void waitBackgroundTasks();
  void send_waitBackgroundTasks();
  void recv_waitBackgroundTasks();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class DatabaseProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<DatabaseIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (DatabaseProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_listEnums(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_storeEnum(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_storeEnums(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_deleteEnum(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_listStructures(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_storeStructure(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_storeStructures(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_deleteStruct(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_listStrings(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_xrefsTo(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_xrefsFrom(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_fetchInstruction(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_listFunctions(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_getFunctionFrame(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_parseTypeDeclaration(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_formatTypeInfo(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_waitBackgroundTasks(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  DatabaseProcessor(boost::shared_ptr<DatabaseIf> iface) :
    iface_(iface) {
    processMap_["listEnums"] = &DatabaseProcessor::process_listEnums;
    processMap_["storeEnum"] = &DatabaseProcessor::process_storeEnum;
    processMap_["storeEnums"] = &DatabaseProcessor::process_storeEnums;
    processMap_["deleteEnum"] = &DatabaseProcessor::process_deleteEnum;
    processMap_["listStructures"] = &DatabaseProcessor::process_listStructures;
    processMap_["storeStructure"] = &DatabaseProcessor::process_storeStructure;
    processMap_["storeStructures"] = &DatabaseProcessor::process_storeStructures;
    processMap_["deleteStruct"] = &DatabaseProcessor::process_deleteStruct;
    processMap_["listStrings"] = &DatabaseProcessor::process_listStrings;
    processMap_["xrefsTo"] = &DatabaseProcessor::process_xrefsTo;
    processMap_["xrefsFrom"] = &DatabaseProcessor::process_xrefsFrom;
    processMap_["fetchInstruction"] = &DatabaseProcessor::process_fetchInstruction;
    processMap_["listFunctions"] = &DatabaseProcessor::process_listFunctions;
    processMap_["getFunctionFrame"] = &DatabaseProcessor::process_getFunctionFrame;
    processMap_["parseTypeDeclaration"] = &DatabaseProcessor::process_parseTypeDeclaration;
    processMap_["formatTypeInfo"] = &DatabaseProcessor::process_formatTypeInfo;
    processMap_["waitBackgroundTasks"] = &DatabaseProcessor::process_waitBackgroundTasks;
  }

  virtual ~DatabaseProcessor() {}
};

class DatabaseProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  DatabaseProcessorFactory(const ::boost::shared_ptr< DatabaseIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< DatabaseIfFactory > handlerFactory_;
};

class DatabaseMultiface : virtual public DatabaseIf {
 public:
  DatabaseMultiface(std::vector<boost::shared_ptr<DatabaseIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~DatabaseMultiface() {}
 protected:
  std::vector<boost::shared_ptr<DatabaseIf> > ifaces_;
  DatabaseMultiface() {}
  void add(boost::shared_ptr<DatabaseIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void listEnums(std::vector<ida_enum> & _return) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->listEnums(_return);
    }
    ifaces_[i]->listEnums(_return);
    return;
  }

  bool storeEnum(const ida_enum& _enum) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->storeEnum(_enum);
    }
    return ifaces_[i]->storeEnum(_enum);
  }

  bool storeEnums(const std::vector<ida_enum> & enums) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->storeEnums(enums);
    }
    return ifaces_[i]->storeEnums(enums);
  }

  void deleteEnum(const std::string& name) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->deleteEnum(name);
    }
    ifaces_[i]->deleteEnum(name);
  }

  void listStructures(std::vector<IdaStruct> & _return) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->listStructures(_return);
    }
    ifaces_[i]->listStructures(_return);
    return;
  }

  bool storeStructure(const IdaStruct& _struct) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->storeStructure(_struct);
    }
    return ifaces_[i]->storeStructure(_struct);
  }

  bool storeStructures(const std::vector<IdaStruct> & structs) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->storeStructures(structs);
    }
    return ifaces_[i]->storeStructures(structs);
  }

  void deleteStruct(const std::string& name) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->deleteStruct(name);
    }
    ifaces_[i]->deleteStruct(name);
  }

  void listStrings(std::vector<ida_string> & _return) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->listStrings(_return);
    }
    ifaces_[i]->listStrings(_return);
    return;
  }

  void xrefsTo(std::vector<IdaRef> & _return, const int32_t address, const IdaRefType::type refType) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->xrefsTo(_return, address, refType);
    }
    ifaces_[i]->xrefsTo(_return, address, refType);
    return;
  }

  void xrefsFrom(std::vector<IdaRef> & _return, const int32_t address, const IdaRefType::type refType) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->xrefsFrom(_return, address, refType);
    }
    ifaces_[i]->xrefsFrom(_return, address, refType);
    return;
  }

  void fetchInstruction(IdaInstruction& _return, const int32_t address) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->fetchInstruction(_return, address);
    }
    ifaces_[i]->fetchInstruction(_return, address);
    return;
  }

  void listFunctions(std::vector<IdaFunction> & _return) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->listFunctions(_return);
    }
    ifaces_[i]->listFunctions(_return);
    return;
  }

  void getFunctionFrame(IdaFunctionFrame& _return, const int32_t address) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getFunctionFrame(_return, address);
    }
    ifaces_[i]->getFunctionFrame(_return, address);
    return;
  }

  void parseTypeDeclaration(IdaTypeInfo& _return, const std::string& typeDeclaration) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->parseTypeDeclaration(_return, typeDeclaration);
    }
    ifaces_[i]->parseTypeDeclaration(_return, typeDeclaration);
    return;
  }

  void formatTypeInfo(std::string& _return, const IdaTypeInfo& typeInfo) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->formatTypeInfo(_return, typeInfo);
    }
    ifaces_[i]->formatTypeInfo(_return, typeInfo);
    return;
  }

  void waitBackgroundTasks() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->waitBackgroundTasks();
    }
    ifaces_[i]->waitBackgroundTasks();
  }

};

} // namespace

#endif
