/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef idaas_CONSTANTS_H
#define idaas_CONSTANTS_H

#include "idaas_types.h"

namespace idaas {

class idaasConstants {
 public:
  idaasConstants();

};

extern const idaasConstants g_idaas_constants;

} // namespace

#endif
