/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "idaas_constants.h"

namespace idaas {

const idaasConstants g_idaas_constants;

idaasConstants::idaasConstants() {
}

} // namespace

